
# ==============================================================================
# Go migrate postgresql

# ==============================================================================
# Swagger Models
models:
	$(call print-target)
	find ./pkg/api/models -type f -not -name '*_test.go' -delete
	swagger generate model -m api -f /pkg/api/swagger/swag.yml -t pkg/api/models

generate: models