// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CountModel count model
//
// swagger:model CountModel
type CountModel struct {

	// sum
	Sum int64 `json:"sum,omitempty"`
}

// Validate validates this count model
func (m *CountModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this count model based on context it is used
func (m *CountModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CountModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CountModel) UnmarshalBinary(b []byte) error {
	var res CountModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
